server.port=8080
spring.application.name=clima-service
spring.threads.virtual.enabled=true

weather.api-key=${key:11111111111111}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=api
spring.mail.password=11111
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



